# Generated by Django 2.1.7 on 2019-03-18 07:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='last_connect_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 7, 8, 14, 113112)),
        ),
        migrations.AddField(
            model_name='player',
            name='registration_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 18, 7, 8, 14, 112954)),
        ),
        migrations.AddField(
            model_name='player',
            name='won_games',
            field=models.IntegerField(default=0),
        ),
    ]
