# Generated by Django 2.1.7 on 2019-03-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0004_auto_20190318_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='last_connect_date',
            new_name='last_connection_date',
        ),
    ]
