# Generated by Django 2.1.7 on 2019-03-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sea_battle', '0005_auto_20190318_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='percent_of_victory',
            field=models.IntegerField(default=0),
        ),
    ]
